[project]
name = "mplayer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.4.1",
    "pygame>=2.6.1",
    "requests>=2.32.3",
]
